//! Shared utilities for integration tests.
//!
//! Include from each test file via `mod common;`.
//! Placed outside `#[cfg(test)]` so integration test crates can also reference it.

#![allow(dead_code)]

use std::fmt::Write as _;

/// Construct an orthorhombic cell matrix [[Lx,0,0],[0,Ly,0],[0,0,Lz]] — f32 version (GPU/CpuEngine).
pub fn ortho_cell(lx: f32, ly: f32, lz: f32) -> [[f32; 3]; 3] {
    [[lx, 0.0, 0.0], [0.0, ly, 0.0], [0.0, 0.0, lz]]
}

/// Construct an orthorhombic cell matrix — f64 version (reference implementation).
pub fn ortho_cell_f64(lx: f64, ly: f64, lz: f64) -> [[f64; 3]; 3] {
    [[lx, 0.0, 0.0], [0.0, ly, 0.0], [0.0, 0.0, lz]]
}

/// Convert a `[[f32; 3]; 3]` cell to `[[f64; 3]; 3]` for use with `compute_eam_cpu`.
pub fn cell_to_f64(h: [[f32; 3]; 3]) -> [[f64; 3]; 3] {
    [
        [h[0][0] as f64, h[0][1] as f64, h[0][2] as f64],
        [h[1][0] as f64, h[1][1] as f64, h[1][2] as f64],
        [h[2][0] as f64, h[2][1] as f64, h[2][2] as f64],
    ]
}

/// Convert a `Vec<[f32; 3]>` position array to `Vec<[f64; 3]>` for use with `compute_eam_cpu`.
pub fn pos3_to_f64(pos: &[[f32; 3]]) -> Vec<[f64; 3]> {
    pos.iter()
        .map(|p| [p[0] as f64, p[1] as f64, p[2] as f64])
        .collect()
}

/// Generates a synthetic Cu-like `.eam.alloy` string for tests.
/// This is not a real Cu potential (simple analytical function).
pub fn synthetic_cu_alloy_src(nr: u32, nrho: u32, dr: f32, drho: f32, cutoff: f32) -> String {
    let mut s = String::new();
    writeln!(s, "# Synthetic Cu potential for CREAM integration tests").unwrap();
    writeln!(s, "# NOT for production use").unwrap();
    writeln!(s, "# Generated by tests/common.rs").unwrap();
    writeln!(s, "1 Cu").unwrap();
    writeln!(s, "{nrho} {drho} {nr} {dr} {cutoff}").unwrap();
    writeln!(s, "29 63.546 3.615 fcc").unwrap();
    // F(rho) = -sqrt(rho + 0.01)
    for i in 0..nrho {
        let rho = i as f32 * drho;
        write!(s, "{:.8e} ", -(rho + 0.01_f32).sqrt()).unwrap();
        if (i + 1) % 5 == 0 {
            writeln!(s).unwrap();
        }
    }
    writeln!(s).unwrap();
    // f(r) = ((cutoff - r) / cutoff)^2  for r < cutoff
    for i in 0..nr {
        let r = i as f32 * dr;
        let v = if r < cutoff {
            let t = (cutoff - r) / cutoff;
            t * t
        } else {
            0.0
        };
        write!(s, "{:.8e} ", v).unwrap();
        if (i + 1) % 5 == 0 {
            writeln!(s).unwrap();
        }
    }
    writeln!(s).unwrap();
    // r*phi(r) where phi(r) = (cutoff - r)^2  — .eam.alloy stores r*phi, not phi
    for i in 0..nr {
        let r = i as f32 * dr;
        let v = if r < cutoff {
            let t = cutoff - r;
            r * t * t
        } else {
            0.0
        };
        write!(s, "{:.8e} ", v).unwrap();
        if (i + 1) % 5 == 0 {
            writeln!(s).unwrap();
        }
    }
    writeln!(s).unwrap();
    s
}

/// Coordinates for an FCC Cu 4-atom unit cell (a = 3.615 Å).
pub fn cu_fcc_4atom_pos3() -> Vec<[f32; 3]> {
    let a = 3.615f32;
    vec![
        [0.0, 0.0, 0.0],
        [a / 2.0, a / 2.0, 0.0],
        [a / 2.0, 0.0, a / 2.0],
        [0.0, a / 2.0, a / 2.0],
    ]
}

/// FCC Cu 4-atom unit cell in GPU `vec4` format.
pub fn cu_fcc_4atom_pos4() -> Vec<[f32; 4]> {
    cu_fcc_4atom_pos3()
        .iter()
        .map(|p| [p[0], p[1], p[2], 0.0])
        .collect()
}

pub fn cu_fcc_4atom_types() -> Vec<u32> {
    vec![0u32; 4]
}

/// Generates a synthetic Cu-Ag binary-alloy `.eam.alloy` string (test-only).
pub fn synthetic_cuag_alloy_src(nr: u32, nrho: u32, dr: f32, drho: f32, cutoff: f32) -> String {
    use std::fmt::Write as _;
    let mut s = String::new();
    writeln!(s, "# Synthetic CuAg potential for CREAM integration tests").unwrap();
    writeln!(s, "# NOT for production use").unwrap();
    writeln!(s, "# Generated by tests/common.rs").unwrap();
    writeln!(s, "2 Cu Ag").unwrap();
    writeln!(s, "{nrho} {drho} {nr} {dr} {cutoff}").unwrap();

    // Cu (Z=29), Ag (Z=47) — verify multi-element behavior with different embedding strengths
    for (z, scale) in [(29u32, 1.0f32), (47, 0.9f32)] {
        writeln!(s, "{z} 63.546 3.615 fcc").unwrap();
        for i in 0..nrho {
            let rho = i as f32 * drho;
            write!(s, "{:.8e} ", -scale * (rho + 0.01_f32).sqrt()).unwrap();
            if (i + 1) % 5 == 0 {
                writeln!(s).unwrap();
            }
        }
        writeln!(s).unwrap();
        for i in 0..nr {
            let r = i as f32 * dr;
            let v = if r < cutoff {
                let t = (cutoff - r) / cutoff;
                scale * t * t
            } else {
                0.0
            };
            write!(s, "{:.8e} ", v).unwrap();
            if (i + 1) % 5 == 0 {
                writeln!(s).unwrap();
            }
        }
        writeln!(s).unwrap();
    }
    // 3 pair tables: Cu-Cu, Cu-Ag, Ag-Ag — r*phi(r) per .eam.alloy format
    for scale in [1.0f32, 0.95, 0.9] {
        for i in 0..nr {
            let r = i as f32 * dr;
            let v = if r < cutoff {
                let t = cutoff - r;
                scale * r * t * t
            } else {
                0.0
            };
            write!(s, "{:.8e} ", v).unwrap();
            if (i + 1) % 5 == 0 {
                writeln!(s).unwrap();
            }
        }
        writeln!(s).unwrap();
    }
    s
}
